name: first_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # تنسيق المسافات البادئة (2 spaces) صحيح تماماً
  assets:
    - assets/in.png
    - assets/Screen.png
    - assets/singin.png
    - assets/singu.png
    - assets/___png.png
    